<a href="https://colab.research.google.com/github/SuryARavichan/PYTHON-FOR-DATA-SCIENCE-BDA-/blob/main/session1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
a=np.array([3,6,7])

In [ ]:
a

array([3, 6, 7])

In [ ]:
print(a)

[3 6 7]


In [ ]:
np.mean(a)

5.333333333333333

In [ ]:
np.sum(a)

16

In [ ]:
1+1
b=2*6
c=5.25/2
print('division:',c)
print('multiplication:',b)


division: 2.625
multiplication: 12


In [ ]:
5*np.log2(7.89)+6.2*np.log2(8.90)

34.453719584883686

In [ ]:
type(c)

float

In [ ]:
type(b)

int

In [ ]:
a=4*5
b=4**16
c=a/b
print('final result of c:',c)
d=True

final result of c: 4.6566128730773926e-09


In [ ]:
type(d)

bool

In [ ]:
d=a>b

In [ ]:
d

False

In [ ]:
d=a<b

In [ ]:
d

True

% - to return the reminder

In [ ]:
result = 5 % 2


In [ ]:
result

1

In [ ]:
(2 + 3) * (5 + 5)

50

In [ ]:
5/2

2.5

In [ ]:
abs(-67)

67

In [ ]:
np.floor(4.9)

4.0

In [ ]:
np.ceil(4.9)

5.0

In [ ]:
np.round(4.8)

5.0

In [ ]:
np.exp(-7)

0.0009118819655545162

In [ ]:
np.log2(0.67)

-0.5777669993169522

In [ ]:
np.log10(6.7)

0.8260748027008264

In [ ]:
np.log(67)

4.204692619390966

In [ ]:
np.exp(np.log(0.5))

0.5

In [ ]:
x=-7.8
y=1/(1+np.exp(-x))
print(y)

0.00040956716498605043


In [ ]:
a=1/(1+np.exp(8.90))

In [ ]:
a

0.00013637032707949703

In [ ]:
print(x+y)
print(x-y)
print(x/y)
print(x%y)
print(x//y)


-7.799590432835013
-7.800409567164986
-19044.495425471086
0.00020665715933067784
-19045.0


In [ ]:
f = "we are learning basics of python"

In [ ]:
f[4]

'r'

In [ ]:
f[26:]

'python'

In [ ]:
f[0]

'w'

In [ ]:
f[:6]


'we are'

In [ ]:
f[0:5]

'we ar'

In [ ]:
f[26:]


'python'

In [ ]:
f[-10:]

' of python'

In [ ]:
f[-6:]

'python'

In [ ]:
len(f)

32

In [ ]:
len(f)-6

26

In [ ]:
f[-6:]

'python'

In [ ]:
f[-9:-8]

'o'

In [ ]:
f[0]

'w'

In [ ]:
f[-9:-7]

'of'

In [ ]:
c = 'surya'

In [ ]:
print(c)

surya


In [ ]:
c

'surya'

In [ ]:
num = 12
name = 'Sam'


In [ ]:
print('My num is: {one}, My name is: {two}'. format(one=num, two=name))

My num is: 12, My name is: Sam


In [ ]:
print('My num is: {}, My name is: {}'.format(num,name))

My num is: 12, My name is: Sam


In [ ]:
print('My num is %d, My name is %s'%(num,name))

My num is 12, My name is Sam


In [ ]:
type(num), type(name)

(int, str)

In [ ]:
st = 'my name is surya'


In [ ]:
st.lower()



'my name is surya'

In [ ]:
st.upper()

'MY NAME IS SURYA'

In [ ]:
c.upper()

'SURYA'

In [ ]:
c

'surya'

In [ ]:
st.title()

'My Name Is Surya'

In [ ]:
st.split()

['my', 'name', 'is', 'surya']

In [ ]:
tweet = 'Go Sports #Sports'



In [ ]:
tweet.split('#')

['Go Sports ', 'Sports']

In [ ]:
tweet.split()

['Go', 'Sports', '#Sports']

In [ ]:
5==4

False

In [ ]:
5>4

True

In [ ]:
5<4

False

In [ ]:
'hi' == 'hello'


False

In [ ]:
(1 < 2) and (3 < 7)

True

In [ ]:
(1 < 2) or (90 < 7)

True

In [ ]:
(1 == 1) and (3 == 3) or (0 == 7)

True

In [ ]:
if(1<4):
  print('it is true')
print('done')

it is true
done


In [ ]:
print('the file has been saved')

the file has been saved


In [ ]:
if(1<2):
  print('number is lesser')
print('done')

number is lesser
done


In [ ]:
if(1<2):
  print('number is lesser')
  print('condition is true')
print('we came out of the loop statement')
print('done')

number is lesser
condition is true
we came out of the loop statement
done


In [ ]:
if 5>2:
  print('5 is greater than 2')
  a=5**2
else:
  print('previous conditions is false')
  b=2**2
print(a)


5 is greater than 2
25


In [ ]:
if 3 == 2:
  print('first')
elif 4 == 4:
  print('middle')
else:
  print('last')
print('all done')

middle
all done


In [ ]:
j=1
while(j<=5):
  print('j is: %d'%j)
  j=j+1
  if j==3:
    break;
  print('finished')

j is: 1
finished
j is: 2


In [ ]:
l=[10,'Surya',78,'Natali',67,'Neha',98]
type(a),len(a)

(list, 5)

In [ ]:
a[:3]

[89, 909090, 7878]

In [ ]:
aa=a[::2]
print(aa)

[89, 7878, 90901]


In [ ]:
a=[89,909090,7878,1678,90901]
np.mean(a)

201927.2

In [ ]:
np.mean(aa)

32956.0

In [ ]:
np.mean([78787,89898989,1676767,8737534676,90928786254,35243178])

16632203108.5

In [ ]:
m=np.array([2.5,4,6.8])

In [ ]:
type(m)

numpy.ndarray

In [ ]:
m

array([2.5, 4. , 6.8])

In [ ]:
a

[89, 909090, 7878, 1678, 90901]

In [ ]:
l

[10, 'Surya', 78, 'Natali', 67, 'Neha', 98]

In [ ]:
l[5] = 'java'

In [ ]:
l

[10, 'Surya', 78, 'Natali', 67, 'java', 98]

In [ ]:
l.append('great britain')

In [ ]:
l

[10, 'Surya', 78, 'Natali', 67, 'java', 98, 'great britain']

In [ ]:
l.pop()

'great britain'

In [ ]:
l

[10, 'Surya', 78, 'Natali', 67, 'java', 98]

In [ ]:
len(l)

7

In [ ]:
o=[]

In [ ]:
o.append('natali')

In [ ]:
o

['natali']

In [ ]:
l.insert(3,'madhuri nayaki')

In [ ]:
l

[10, 'Surya', 78, 'madhuri nayaki', True, 'Natali', 67, 'java', 98]

In [ ]:
l.insert(8,'67')

In [ ]:
l

[10, 'Surya', 78, 'madhuri nayaki', True, 'Natali', 67, 'java', '67', 98]

In [ ]:
l.pop(5)

'Natali'

In [ ]:
l

[10, 'Surya', 78, 'madhuri nayaki', True, 67, 'java', '67', 98]

In [ ]:
np.median(aa)

7878.0

In [ ]:
np.std(aa)

41096.507548290116

In [ ]:
np.var(aa)

1688922932.6666667

In [ ]:
np.min(aa),np.argmax(aa)


(89, 2)

In [ ]:
np.max(aa),np.argmax(aa)

(90901, 2)

In [ ]:
x=[10,20,30]

In [ ]:
x


[10, 20, 30]

shallow copy - the modifying changes occurs in both a and b

In [ ]:
y=x

In [ ]:
y

[10, 'united states', 30]

In [ ]:
x

[10, 'united states', 30]

In [ ]:
y[1] = 'united states'

In [ ]:
y

[10, 'united states', 30]

In [ ]:
x

[10, 'united states', 30]

**deep** ***copy***

In [ ]:
import copy
y=copy.deepcopy(x)

In [ ]:
x

[10, 'united states', 30]

In [ ]:
y

[10, 'united states', 30]

In [ ]:
x[0] = 'germany'

In [ ]:
x

['germany', 'united states', 30]

In [ ]:
y

[10, 'united states', 30]